config/routes.rb
Rails.application.routes.draw do
  scope 'admins' do
    use_doorkeeper
  end

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

  devise_scope :user do
    authenticated :user do
      root 'users/welcome#show', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api do
    namespace :v1 do
      resource :owner, only: :show
    end
  end

  namespace :admins do
    resources :users, only: [:index, :edit, :update]
    resources :clients
  end
end

app/models/admins.rb
module Admins
  def self.table_name_prefix
    "admins_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :users

	validates :name, presence: true
end

app/models/login_provider.rb
class LoginProvider < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :login_providers, dependent: :destroy
  belongs_to :client

  enum :role, [:client, :admin]

  def valid_password?(password)
    password.blank? ? true : super
  end

  def password_required?
    new_record? ? false : super
  end
end

app/controllers/admins/base_controller.rb
# frozen_string_literal: true

class Admins::BaseController < ApplicationController
	before_action :authenticate_admin!
	layout 'admin'

  private

  def authenticate_admin!
  	return if current_user.admin?

  	authenticated_root_path
  end
end

app/controllers/admins/clients_controller.rb
class Admins::ClientsController < Admins::BaseController
  before_action :set_client, only: %i[ show edit update destroy ]

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to admins_clients_url, notice: "Client was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @client.update(client_params)
      redirect_to admins_clients_url, notice: "Client was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @client.destroy

    redirect_to admins_clients_url, notice: "Client was successfully destroyed."
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :extra_fields)
    end
end

app/controllers/admins/users_controller.rb
# frozen_string_literal: true

class Admins::UsersController < Admins::BaseController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_users_url, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :first_name, :last_name)
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

class Api::V1::BaseController < ApplicationController
	before_action :doorkeeper_authorize!
  respond_to :json
end

app/controllers/api/v1/owners_controller.rb
# frozen_string_literal: true

class Api::V1::OwnersController < Api::V1::BaseController
  def show
    respond_with current_resource_owner
  end

  private

  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

 	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:client_id, :email, :password)}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = ::SetUserLoginProviderService.call(auth)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to unauthenticated_root_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    unauthenticated_root_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || authenticated_root_path
  end

  private

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    unauthenticated_root_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || authenticated_root_path
  end
end

app/controllers/users/welcome_controller.rb
# frozen_string_literal: true

class Users::WelcomeController < Devise::SessionsController
  def show
  end
end

app/helpers/admins/clients_helper.rb
module Admins::ClientsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/clients/_client.html.erb
<tr>
  <td><%= link_to client.name, edit_admins_client_path(client) %></td>
  <td><%= client.extra_fields %></td>
  <td><%= button_to "Delete", admins_client_path(client), method: :delete, class: "btn btn-danger", data: { turbo: false, confirm: 'Are you sure?' } %></td>
</tr>

app/views/admins/clients/_form.html.erb
<%= form_with(model: [:admins, @client]) do |form| %>
  <% if @client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% @client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :extra_fields, style: "display: block" %>
    <%= form.text_field :extra_fields, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit 'Save', class: "btn btn-success" %>
  </div>
<% end %>

app/views/admins/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", admins_client: @client %>

app/views/admins/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<%= link_to "New client", new_admins_client_path, class: "btn btn-success" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th>Extra Fields</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <%= render client %>
    <% end %>
  </tbody>
</table>

app/views/admins/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

app/views/admins/users/edit.html.erb
<h1>Editing User</h1>

<%= form_with(model: [:admins, @user]) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% @client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, class: "form-control" %>
  </div>

  <% @user.extra_information.each do |field, value| %>
	  <div class="form-group mt-3">
      <%= form.label field, field.humanize, style: "display: block" %>
      <%= form.text_field field, value: value, class: "form-control", disabled: true %>
    </div>
  <% end %>

  <div class="form-group mt-3">
    <%= form.submit 'Save', class: "btn btn-success" %>
  </div>
<% end %>

app/views/admins/users/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, edit_admins_user_path(user) %></td>
        <th><%= user.role %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <header class="mb-4">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <!-- Container wrapper -->
          <div class="container-fluid">
            <!-- Toggle button -->
            <button
              class="navbar-toggler"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#navbarCenteredExample"
              aria-controls="navbarCenteredExample"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div
              class="collapse navbar-collapse justify-content-center"
              id="navbarCenteredExample"
            >
              <!-- Left links -->
              <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to 'Applications', oauth_applications_path, class: "nav-link active", "aria-current": "page" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Users', admins_users_path, class: "nav-link active", "aria-current": "page" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Clients', admins_clients_path, class: "nav-link active", "aria-current": "page" %>
                </li>
                <li class="nav-item">
                  <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", data: { turbo: false } %>
                </li>
              </ul>
              <!-- Left links -->
            </div>
            <!-- Collapsible wrapper -->
          </div>
          <!-- Container wrapper -->
        </nav>
      </header>

      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <header class="mb-4">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <!-- Container wrapper -->
            <div class="container-fluid">
              <!-- Toggle button -->
              <button
                class="navbar-toggler"
                type="button"
                data-mdb-toggle="collapse"
                data-mdb-target="#navbarCenteredExample"
                aria-controls="navbarCenteredExample"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <i class="fas fa-bars"></i>
              </button>

              <!-- Collapsible wrapper -->
              <div
                class="collapse navbar-collapse justify-content-center"
                id="navbarCenteredExample"
              >
                <!-- Left links -->
                <ul class="navbar-nav mb-2 mb-lg-0">
                  <% if current_user.admin? %>
                    <li class="nav-item">
                      <%= link_to 'Admin Panel', oauth_applications_path, class: "nav-link", "aria-current": "page" %>
                    </li>
                  <% end %>
                  <li class="nav-item">
                    <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", data: { turbo: false } %>
                  </li>
                </ul>
                <!-- Left links -->
              </div>
              <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
          </nav>
        </header>
      <% end %>
      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/users/welcome/show.html.erb
<h2 class="text-center">
	Welcome
	<span class="text-primary"><%= current_user.email %></span>
</h2>